---
lang: es
output:
  word_document:
    reference_docx: formato_1.docx
    toc: yes
    fig_caption: yes
toc-title: Tabla de contenido
csl: apa.csl
bibliography: bibliografia.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F, fig.height = 3, fig.width = 6, results='asis')


library(tidyverse)
library(tidymodels)
library(haven)
library(pglm)
library(survival)
library(flextable)
library(sandwich)
library(modelsummary)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(countrycode)

set_flextable_defaults(
  font.size = 10,
  font.family = "Garamond",
  theme_fun = "theme_zebra")

datos_tesis <- read_rds("~/GitHub/tesis/datos/datos_tesis.rds")
juicios <- read_dta("~/GitHub/tesis/datos/barsbargains_replication/barsbargains.dta")
datos_tesis <- datos_tesis %>% left_join(juicios %>% select(pais = country, anno = year, codigo_transicion = dtr_id, amnistias_dummy = ambin))
```

# INTRODUCCIÓN

Durante los últimos cuatro años, diferentes países de América Latina y el Caribe experimentaron situaciones de inestabilidad política que provocaron un importante retroceso en materia de derechos humanos. En Chile, en el contexto de las protestas masivas de 2019, organismos internacionales denunciaron el uso ilegal de armas mortales y la aplicación de torturas y vejaciones sexuales hacia los manifestantes por parte de las fuerzas de orden y seguridad  [@AI2020; @HRW2020].[^1] Ese mismo año, Bolivia enfrentó tensiones políticas que desencadenaron la violencia estatal, generando miles de denuncias de abusos a los derechos humanos en el contexto postelectoral [@HRW2020].[^2] En Venezuela, Honduras, Guatemala y Nicaragua, se registraron situaciones análogas, con informes de violencia sexual, asesinatos y desapariciones forzadas, a menudo imbricadas en conflictos sociales y políticos [@AI2020].[^3] En 2020, Colombia y México registraron un aumento en los asesinatos de líderes sociales y defensores de derechos humanos [@AI2021], mientras que en Brasil, el gobierno de Bolsonaro fue acusado de implementar políticas represivas hacia grupos medioambientalistas y sectores vulnerables de la población [@HRW2021].[^4]

En varios casos, el retroceso se está dando en países que cuentan con un historial reciente de violaciones graves a los derechos humanos y que han implementado durante los últimos 30 o 40 años un conjunto de medidas de justicia transicional para tratar con sus pasados violentos y autoritarios, y prevenir la ocurrencia de nuevas atrocidades. En este contexto, políticos, académicos y activistas se preguntan si la justicia transicional ayudó realmente a la prevención de nuevas violaciones a los derechos humanos, o si el retroceso que actualmente viven los países de América Latina y el Caribe con regímenes post autoritarios se está dando a pesar de las disposiciones de la justicia transicional. Sin embargo, el desarrollo actual del campo de investigación no permite responder adecuadamente esta interrogante.

Los estudios realizados hasta ahora ofrecen resultados y conclusiones inconsistentes sobre la eficacia histórica de los mecanismos de justicia transicional (enjuiciamientos, amnistías y comisiones de la verdad) en la consolidación de la democracia y la protección de los derechos humanos. Los estudios de Kim & Sikkink (2010) y Dancy et al. (2019), informan de una relación positiva entre el enjuiciamiento de criminales de lesa humanidad y el nivel de protección de los derechos de integridad física en las democracias post autoritarias, mientras que los estudios de Snyder & Vinjamuri (2003, 2015) sugieren un efecto contrario, vinculando los enjuiciamientos con un aumento de la represión estatal. Respecto a las amnistías, es decir, a las políticas estatales de perdón e impunidad por violaciones a los derechos humanos, la evidencia presentada por Snyder & Vinjamuri (2003) indica que éstas tienen un impacto positivo en la promoción de la democracia y la prevención de abusos estatales, mientras que el estudio de Dancy et al. (2019) las relaciona con mejoras en el ejercicio de libertades civiles, pero no con la disminución de la violencia institucional. En el caso de las comisiones de la verdad, vale decir, las medidas extra judiciales de justicia transicional, los resultados también son mixtos: El estudio de Olsen, Payne, & Reiter (2010) plantea que las comisiones tienen un impacto negativo en la protección de los derechos humanos, mientras Dancy & Thoms (2022) presentan evidencia contraria que describe una relación positiva entre el uso de este mecanismo de justicia transicional y los niveles de respeto a los derechos humanos. Los estudios también divergen en cuanto al impacto combinado de enjuiciamientos, amnistías y comisiones de la verdad. Mientras Olsen, Payne, & Reiter (2010) sugieren que esta combinación fortalece la democracia y la protección de los derechos humanos al equilibrar la rendición de cuentas con los imperativos de estabilidad política, el estudio de Dancy et al. (2019) no encuentra beneficios significativos en los países que utilizaron estos mecanismos conjuntamente.

La inconsistencia en los hallazgos y resultados producidos por los estudios anteriores puede estar relacionado con tres factores clave del diseño de investigación. En primer lugar, se identifica una notable ausencia de consenso en torno a las definiciones y métricas aplicadas a los mecanismos de justicia transicional. Mientras algunos investigadores adoptan un enfoque inclusivo que abarca una variedad de actores en procesos judiciales vinculados a delitos comunes y violaciones de derechos humanos, otros restringen su análisis exclusivamente a la persecución de crímenes cometidos por agentes estatales. Esta variabilidad conceptual se extiende a la caracterización y alcance de las comisiones de la verdad, donde las divergencias en criterios de inclusión de casos específicos añaden complejidad al panorama investigativo. En segundo lugar, las investigaciones anteriores han utilizado diferentes variables dependientes para evaluar el impacto de la justicia transicional en la consolidación de la democracia y la protección de los derechos humanos. Esta divergencia de variables e indicadores de resultado se evidencia particularmente en la utilización de distintas escalas y dimensiones de democracia, algunas de las cuales pueden no alinearse directamente con los objetivos intrínsecos de los mecanismos de justicia transicional, generando problemas para el establecimiento de relaciones causales. En tercer lugar, existe disparidad en los estudios comparados respecto al conjunto específico de casos a analizar. Mientras algunos se centran en países con transiciones democráticas o post-conflicto, otros abarcan ambos escenarios. Esta variación en la selección de casos conduce a interpretaciones heterogéneas que dificultan el alcance y la generalización de resultados.

Los factores de inconsistencia señalados anteriormente, representan importantes desafíos para la investigación empírica sobre la contribución de los mecanismos de justicia transicional a la democracia y la protección de los derechos humanos. En la presente tesis se abordan estos desafíos a través de una estrategia de investigación rigurosa, que se apoya en definiciones precisas, datos homogéneos y métricas robustas para evaluar el impacto de los enjuiciamientos, amnistías y comisiones de la verdad en las democracias post autoritarias.

Para garantizar coherencia en la definición y medición de variables clave, la tesis se fundamenta en el derecho internacional de los derechos humanos y en los indicadores desarrollados por el Transitional Justice Research Collaborative (TJRC). Dicha base conceptual permite una interpretación clara de los mecanismos de justicia transicional como herramientas sociales destinadas a abordar las secuelas de regímenes autoritarios caracterizados por violaciones sistemáticas de derechos humanos. El TJRC, a través de su base de datos detallada, facilita la cuantificación precisa de enjuiciamientos (con y sin sentencias condenatorias), amnistías y comisiones de la verdad, ofreciendo así una perspectiva integral y matizada de cada mecanismo. 

Además, la tesis presenta modelos analíticos que se centran en evaluar la incidencia de los mecanismos de justicia transicional en la estabilidad democrática y la protección de derechos humanos. Específicamente, se investiga la relación entre la implementación de enjuiciamientos, amnistías y comisiones de la verdad, y la ocurrencia de golpes de Estado, así como la variabilidad en la protección latente de los derechos de integridad física. Estos modelos buscan ofrecer una comprensión más profunda y contextualizada de cómo la justicia transicional puede influir en la consolidación democrática y garantizar el ejercicio de derechos fundamentales. 

En aras de la comparabilidad y relevancia de los casos de estudio, la tesis se concentra en los países de América Latina y el Caribe que experimentaron transiciones democráticas entre 1970 y 2010. Esta selección de casos se justifica en la similitud de contextos autoritarios previos en la región, marcados por el ejercicio del terrorismo de estado y el combate al comunismo internacional. Al restringir el análisis a este conjunto de países y períodos, se pretende reducir el sesgo de variable omitida y facilitar el establecimiento de relaciones causales claras entre los mecanismos de justicia transicional, la democracia y la derechos humanos, asumiendo que estos resultados no son generalizables a otras regiones y contextos de transición.

En base al diseño de investigación presentado, el objetivo general de la tesis fue evaluar la contribución de los mecanismos de justicia transicional a la prevención de golpes de estado y la protección de los derechos humanos en los países de América Latina y el Caribe que experimentaron transiciones democráticas entre los años 1970 y 2010. Como se verá más adelante, la limitación temporal del estudio está dada por la disponibilidad de datos estadísticos sobre enjuiciamientos, sentencias, amnistías y comisiones de la verdad, los cuales se reducen al periodo trabajado por el TJRC. Esta limitación implica que el análisis desarrollado no puede abordar eventos más recientes o futuros de justicia transicional y, por tanto, su vínculo con la prevención de golpes de estado y la protección de los derechos humanos. Sin embargo, los datos disponibles en TJRC aún son útiles para analizar sociológicamente la contribución histórica de las medidas de verdad, justicia, reparación y garantías de no repetición.

Para cumplir con el objetivo señalado, se formularon siete hipótesis de investigación basadas en las teorías de alcance medio sobre el impacto de los enjuiciamientos, amnistías y comisiones. Dichas hipótesis se pusieron a aprueba a través de modelos de regresión para datos de series temporales transversales. En específico se estimaron coeficientes de regresión logística de la probabilidad de ocurrencia de golpes de estado y coeficientes de regresión lineal del puntaje de protección latente de los derechos de integridad física, en función del número de enjuiciamientos, amnistías y comisiones de la verdad acumuladas en los años posteriores a la transición democrática. La estimación de los coeficientes se hizo sobre una muestra de 17 países (N) con diferentes años de transición acumulados durante el periodo de estudio (T = 14-37). En todos los modelos, se incluyeron variables de efecto fijo por país e indicadores de control estadísticos vinculados al crecimiento económico, al nivel de democracia, al tamaño de la población, al nivel de independencia del poder judicial, al historial represivo de las naciones y a la existencia de conflictos armados durante los periodos post autoritarios. Los resultados de los modelos se presentan en el texto a través tablas y figuras que visualizan el impacto de cada mecanismo de justicia transicional en las variables de resultado.

En términos generales, el proceso de investigación desarrollado en esta tesis se describe en cuatro capítulos. El primero, muestra el trabajo de construcción del objeto de estudio, donde se detalla la comparación de resultados obtenidos en las investigaciones anteriores, se detectan los factores de inconsistencia y se proponen caminos para superar los desafíos conceptuales y metodológicos. El segundo capítulo formaliza los objetivos específicos de la tesis en función del diseño general de investigación. El tercero, presenta la discusión teórica actual y formula las hipótesis de evaluación de los mecanismos de justicia transicional. El cuarto capítulo, informa los resultados de los modelos regresión que someten a pruebas las hipótesis. Y el quinto y último capítulo, discute teóricamente los hallazgos obtenidos y establece las conclusiones del estudio.

[^1]: El Instituto de Derechos Humanos (INDH) presentó un total de 2.520 querellas por violaciones a los derechos humanos en todo Chile, que consideran a 3.203 víctimas de vulneraciones al derecho a la vida y a la integridad física, por hechos ocurridos entre el 18 de octubre de 2019 y el 18 de marzo de 2020, en el contexto de las movilizaciones contra el gobierno de Sebastián Piñera. Más información en: https://t.ly/npRy-.

[^2]:Según la  Comisión Interamericana de Derechos Humanos (CIDH), al 17 de noviembre de 2019, 23 personas habían perdido la vida y más de 700 resultaron heridas en el contexto de las protestas iniciadas tras las elecciones del 20 de octubre. Más información en: https://www.hrw.org/es/world-report/2020/country-chapters/bolivia

[^3]: En Venezuela, según Amnistía Internacional, las fuerzas de seguridad efectuaron entre enero y septiembre 488 presuntas ejecuciones extrajudiciales. Más información en: https://amnistia.cl/americas-el-doble-rasero-y-las-respuestas-insuficientes-han-menoscabado-los-derechos-humanos/

[^4]: Según Human Rights Watch, la policía brasileña mató a 6.400 personas en 2020, la mayor cifra registrada a la fecha. Cerca del 80 % de las víctimas fueron personas negras. Más información en: https://www.hrw.org/es/news/2022/01/13/america-latina-retroceso-alarmante-de-libertades-basicas
