---
lang: es
output:
  word_document:
    reference_docx: formato_1.docx
    toc: yes
    fig_caption: yes
toc-title: Tabla de contenido
csl: apa.csl
bibliography: bibliografia.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F, fig.height = 3, fig.width = 6, results='asis')

```

# ESTADO DEL ARTE Y PROBLEMA DE ESTUDIO

En el siguiente capítulo, se analiza la literatura existente sobre jusiticia transicional, democracia y protección de los derechos humanos en las democracias post autoritarias, con un enfoque particular en el impacto de los enjuiciamientos, amnistías y comisiones de la verdad. Para lograr esto, se revisan los estudios clave del campo y se destacan las razones detrás de las divergencias de resultados. A continuación, se exploran los factores que contribuyen a estas inconsistencias. Y, finalmente, se presenta una propuesta de investigación que busca evaluar estadísticamente la contribución de los mecanismos de justicia transicional a la consolidación de la democracia y la protección de los derechos humanos en América Latina y el Caribe.


## 1. Estudios anteriores sobre justicia transicional, democracia y protección de los derechos humanos

Durante los últimos 20 años se han desarrollado cinco importantes estudios cuantitativos que analizan estadísticamente la contribución de los enjuiciamientos, amnistías y comisiones de la verdad a la democracia y la protección de los derechos humanos en los regímenes democráticos post autoritarios y post conflicto [@Dancy2010a; @Stewart2017; @Thoms2010]. Estos estudios generaron teorías de alcance medio e hipótesis de investigación que han sido replicadas en los análisis posteriores desarrollador por los académicos que reúnen y sistematizan información sobre el uso de mecanismos de justicia transicional a nivel de países.

El primer estudio fue realizado por @Snyder2003 y centró en analizar empíricamente el impacto de la justicia transicional sobre la protección de la democracia y los derechos humanos en 32 países que experimentaron guerras civiles en el periodo 1989-2003. Para ello, los autores contruyeron una base de datos con indicadores que dan cuenta del uso de enjuiciamientos, amnistías y comisiones de la verdad en el periodo posterior al término del conflicto.

Para medir el impacto de la justicia transicional en el respeto de la democracia y los derechos humanos, @Snyder2003 utilizaron como variable dependiente dos indicadores del nivel de democracia y de garantía de libertades civiles, provenientes de la base de datos de Freedom House y Polity IV. A través de estos indicadores, los autores operacionalizan los conceptos centrales del estudio, y evaluan cómo las tendencias en el nivel de respeto a la democracia y los derechos humanos se correlacionan con las estrategias de justicia transicional utilizadas en los caso de estudio [@Snyder2003, p. 18].

Los resultados obtenidos por @Snyder2003 muestran que las estrategias basadas en el enjuiciamiento de criminales de lesa humanidad impactan negativamente en la protección de la democracia y los derechos humanos, ya que aumentan el riesgo de enfrentar nuevas atrocidades o golpes de estado en el corto plazo, sobre todo cuando los potenciales saboteadores del proceso guardan importantes cuotas de poder institucional. En cambio, las estrategias más pragmáticas o realistas, basados en la negociación política, las amnistías selectivas y el fortalecimiento institucional a largo plazo tienen más posibilidades de reducir la tensión política, consolidar la democracia y garantizar el respeto de los derechos humanos.

En la misma línea los resultados del estudio de @Snyder2003 sugieren que el uso de comisiones de la verdad genera un impacto positivo en la protección de los derechos humanos sólo cuando va acompañado de amnistías para los responsables de las atrocidades. Si esta condición no se cumple, o se combina el uso de comisiones con enjuiciamientos, los países enfrentarán más golpes de estado o ataques armados contra la población civil, y reducirán su nivel de protección de los derechos humanos.

A través de un enfoque pragmático, @Snyder2003 interpretan los resultados de su estudio en favor en las estrategias realistas de justicia transicional. Argumentan que la estabilidad del orden político de un país que atravesó recientemente por una guerra civil, se basa en la negociación política entre grupos contendientes y en la creación de instituciones administrativas sólidas que puedan hacer cumplir la ley bajo los estándares del estado de derecho. La prevención de atrocidades y el aumento del respeto por la ley dependen con frecuencia de llegar a acuerdos políticamente convenientes para ambas partes. La amnistía, o simplemente ignorar los abusos del pasado, puede ser una herramienta necesaria en esta negociación. En cambio, implementar medidas de rendición de cuentas por los abusos del pasado, sin considerar la realidad política local, puede alterar el equilibrio de intereses políticos dominantes y aumentar el riesgo de sufrir golpes de estado, deteriorando significativamente la protección de los derechos humanos.

El segundo estudio importante fue realizado por @Kim2010. El objetivo de este estudio fue analizar la relación entre los juicios por violaciones de derechos humanos (nacionales y extranjeros) y el nivel de protección a los derechos de integridad física, considerando también el uso de comisiones de la verdad como variable de control.

La muestra utilizada por @Kim2010 considera un total de 93 países en transición, que pasaron desde autocracias o guerras civiles hacia regímenes democráticos o semidemocráticos, o que fueron creados después de la disolución de un estado autocrático, entre los años 1980 y 2004. El nivel de respeto a los derechos humanos es analizado mediante el índice de derechos de integridad física de Cingranelli-Richards (CIRI), mientras que los juicios por violaciones de derechos humanos son operacionalizados en dos variables diferentes: una variable dicotómica que indica si un país tuvo un enjuiciamiento nacional o extranjero en algún momento después de la transición, y una variable numérica que cuenta los años de enjuiciamientos acumulados por país. Las comisiones de la verdad, por su parte, son medidas a través de una variable dicotómica que refleja experiencia anterior y posterior al uso de este mecanismo a través de los años de transición, considerando el hecho de que existen países que descartan una política institucional para establecer una verdad histórica sobre los abusos del pasado. Para el resto de las variables de control, el estudio incorpora indicadores ampliamente aceptados de democracia, guerras internacionales, guerras civiles, ratificación de tratados, posición económica del país dentro de la región, crecimiento económico, tamaño de la población y crecimiento de la población.

Los resultados del estudio @Kim2010 proporcionan un panorama positivo sobre la relación entre enjuiciamientos penales y protección de los derechos humanos en los países en transición. En concreto, los resultados muestran que los países con enjuiciamientos tienen mejores niveles de protección de los derechos humanos que los países sin enjuiciamientos, y que los países que han experimentado más enjuiciamientos a lo largo del tiempo tienen una mayor protección de los derechos humanos que los países que tuvieron menos años de enjuiciamientos. Además, los resultados muestran que la experiencia de una comisión de verdad también tiene una relación positiva con la protección de los derechos humanos. Esto quiere decir, que los países que implementaron comisiones de la verdad tuvieron menores niveles de represión durante el periodo de transición que los países que no hicieron uso de este mecanismo.

@Kim2010 explican sus hallazgos apoyándose en la teoría constructivista de la disuasión. Esta teoría plantea que los enjuiciamientos y las comisiones de la verdad contribuyen a la protección de los derechos humanos en las democracias post autoritarias porque aumentan los costos penales y simbólicos asociados al uso de la represión estatal [@Sikkink2011; @Sikkink2013]. Ambos mecanismos comunican a los agentes del Estado que, en caso de cometer violaciones de derechos humanos, serán perseguidos por los tribunales y serán desacreditados públicamente por los organismos encargados de investigar dichos abusos.

El tercer estudio macro cuantitativo sobre la contribución de los mecanismos de justicia transicional a la democracia y la protección de los derechos humanos fue publicado por @Olsen2010a. El objetivo principal de este estudio es analizar la relación entre el uso -individual y combinado- de juicios, amnistías y comisiones de la verdad, y los niveles de democracia y protección de los derechos de integridad física reportados en los países en transición. 

@Olsen2010a utilizan una muestra que incluye 91 transiciones políticas del autoritarismo a la democracia, ocurridas en 74 países del mundo entre los años 1970 y 2004. La medición del respeto o protección de los derechos humanos se realiza a través de dos indicadores diferentes: el índice de derechos de integridad física de Cingranelli-Richards (CIRI) y la escala de terror político (PTS) del departamento de Ciencia Política de la Universidad de Carolina de Norte (USA). El nivel de democracia también es medido a través de dos indicadores diferentes: el índice Polity 2 del conjunto de datos Polity IV, y el Índice de Democracia Liberal del proyecto Freedom House. Por su parte, el uso de amnistías, comisiones de la verdad y enjuiciamientos, se mide a través de variables dicotómicas que dan cuenta de la vigencia de cada uno de estos mecanismos durante los años de transición y también de manera acumulada a lo largo del tiempo. Como variables de control se incluye el PIB, la región, y el nivel de democracia de los países.

Los hallazgos obtenidos por Olsen, Payne y Reiter difieren significativamente de los resultados del estudio de @Kim2010. El estudio de Olsen y sus colegas muestra que, en general, la adopción de los mecanismos de justicia transicional se relaciona positivamente con los niveles de democracia y protección de los derechos humanos, pero ninguno de estos mecanismos por sí sólo logra prevenir el uso de la violencia estatal y el deterioro de las instituciones democráticas [@Olsen2010a, p. 996]. Ni los juicios, ni las amnistías tienen una asociación positiva con los niveles de democracia y respeto a los derechos humanos, y las comisiones de la verdad parecen estar asociadas con un aumento de la represión estatal. Sin embargo, dos combinaciones de mecanismos de justicia transicional si muestran una relación positiva y estadísticamente fuerte con el nivel de respeto a los derechos humanos en los países en transición: (1) la combinación de juicios y amnistías, y (2) la combinación de juicios, amnistías y comisiones de la verdad. Lo mismo ocurre con la asociación entre justicia transicional y democracia, ya que solo el uso combinado de (1) juicios y amnistía, y (2) comisiones de la verdad y aministía, genera un aumento en el nivel de democratización.

@Olsen2010a explican los hallazgos de su investigación apoyándose en la teoría del equilibrio de la justicia transicional. Esta teoría, plantea que la combinación de juicios y amnistías genera un equilibrio que contribuye a los objetivos de la democracia y los derechos humanos, ya que permite satisfacer una parte importante de la demanda por justicia levantada por las víctimas y sus familiares, sin activar a los potenciales saboteadores del proceso de transición que podrían perpetrar un nuevo golpe de estado. Bajo este supuesto, Olsen y sus colegas plantear que la estabilidad a corto plazo que brindan las amnistías no impide el beneficio a largo plazo de la rendición de cuentas a través del enjuiciamiento de criminales de lesa humanidad. Es decir, la secuencia de la amnistía y los juicios a lo largo del tiempo sería la fórmula más razonables de garantizar el respeto de los derechos humanos en los regímenes post autoritarios, sin poner en riesgo la democracia [@Olsen2010a]. En la misma línea, los autores plantean que, por si solas, las comisiones de la verdad impactan negativamente en la protección de los derechos humanos porque no logran promover la rendición de cuentas ni generar estabilidad política en el proceso de transición. Pero si las comisiones de la verdad se combinan con enjuiciamientos y amnistías mejoraran los niveles de democracia y protección de los derechos humanos en el corto y largo plazo, ya que contribuyen a reforzar el equilibrio de la justicia transicional [@Olsen2010].

El cuarto estudio sobre justicia transicional y protección de los derechos humanos fue realizado recientemente por @Dancy2019. Este estudio analiza la contribución de los juicios y amnistías a la protección de los derechos de integridad física y las libertades civiles y políticas en los países con democracias post autoritarias. 

La muestra utilizada por @Dancy2019 selecciona dos tipos de casos:  los casos de estados democráticos recién formados y los casos de estados que pasan de la autocracia a regímenes semi o totalmente democráticos. En total, la base de datos contiene 111 transiciones democráticas ocurridas en 89 países, entre los años 1970 y 2010. El nivel de respeto a los derechos de humanos es medido a través del índice de derechos de integridad física Cingranelli-Richards (CIRI), y el nivel de protección de las libertades civiles y políticas es medido través de índice de derechos de empoderamiento de la misma base de datos. Los enjuiciamientos penales y las amnistías son medidas a través de variables numéricas que indican la cantidad de mecanismos de justicia transicional vigentes para cada año de transición y de manera acumulada. Además, se incorporan una variable que cuenta los veredictos de culpabilidad en el año en que la sentencia fue emitida por primera vez por un tribunal. Estas sentencias son acumuladas en el tiempo de transición de la misma manera que los juicios y las amnistías vigentes. En cuanto a las variables de control, el estudio de @Dancy2019 incorpora indicadores de quiebre democrático, independencia del poder judicial, guerra civil, años de transición, PIB per cápita, tamaño de la población, y nivel de protección de los derechos humanos antes de la transición.

A diferencia de los resultados obtenidos por @Olsen2010a, la evidencia presentada por @Dancy2019 muestra que los enjuiciamientos y los veredictos de culpabilidad están asociados con un aumento significativo en los niveles de protección de los derechos de integridad física, mientras que las amnistías se asocian con una menor violación de las libertades civiles y políticas. Sin embargo, la combinación de ambos mecanismos no genera efectos positivos en los derechos analizados. Es decir, la combinación de juicios y amnistías no mejora los niveles de protección de derechos de integridad física, ni el respeto de las libertades civiles y políticas en las democracias post autoritarias. Esto demuestra que los enjuiciamientos y las amnistías, por si solas, contribuyen a distintos objetivos políticos del proceso de transición, aunque estos no sean necesariamente coherentes ni compatibles entre si [@Dancy2019]. Según @Dancy2019, los hallazgos de su investigación pueden usarse para informar un nuevo enfoque de la justicia transicional, uno basado no en la deliberación democrática o el legalismo formal, sino en lo que algunos teóricos denominan "agonismo" [@Mouffe2014]. Tal enfoque reconocería la naturaleza irreductiblemente impugnada de la acción política y legal realizada en nombre de la justicia transicional, al tiempo que vería en esa impugnación la fuente del pluralismo y el cambio productivo.

El quinto y último estudio sobre justicia transicional y protección de los derechos humanos en las democracias post autoritarias fue realizado por @Dancy2022. Este estudio analiza la relación entre el uso de comisiones de la verdad y el fortalecimiento de las instituciones y prácticas democráticas de los países en transición, entre las que se incluye el respeto por los derechos de integridad física.

@Dancy2022, utilizan una muestra que incluye tres tipos de casos: 1) países que transitaron desde dictaduras o guerras civiles hacia regímenes democráticos o semidemocráticos, 2) países cuya institucionalidad democrática fue creada o reconstruida luego de la disolución de un estado autocrático, y 3) países democráticos que experimentaron guerras civiles o conflictos armados internos. En total, la muestra incluye 92 países que experimentaron transiciones o guerras civiles entre los años 1970 y 2015. El nivel de respeto a los derechos humanos es medido a través del indicador de integridad física latente de Schnakenberg y Fariss, y el nivel democracia es medido a través de dos indicadores proveniente de la base de datos del proyecto v-dem que dan cuenta de los cambios de las instituciones y los comporamientos democráticos: el índice de reforma democrática liberal (calculado en base en base a transformaciones institucionales afectan la obtención elecciones limpias, de libertad sindical, de rendición de cuentas y transparencia pública, y de respeto a las libertades civiles y políticas de las minorías), y el índice de comportamiento democrático (que combina índicadores que miden la participación de la sociedad civil, el voto popular directo y el poder de los gobiernos subnacionales electo). El uso de comisiones de la verdad es medido a través de un conjunto de indicadores que dan cuenta de sus operaciones en los procesos de transición, y de su nivel de éxito o fracaso. El primer indicador da cuenta de la realización de una comisión de verdad, incluido aquellas que no culminaron su trabajo o que se disolvieron sin producir resultados observables. El segundo indicador da cuenta de la existencia o inexistencia de un informe final emitido por una comisión de verdad. El tercero da cuenta de la publicación oficial de dicho informe (de manera impresa o digital). Y el cuarto indicador señala si el informe publicado incluye o no recomendaciones para reformas institucionales o enjuiciamiento de violadores de derechos humanos (ambas medidas de forma separada). En cuanto a las variables de control, el estudio incorpora el PIB per cápita, el tamaño de la población y la presencia o ausencia de conflictos armados en los países.

A diferencia de lo planteado por @Olsen2010a, los resultados del estudio de @Dancy2022 muestran -en primer lugar- la existencia de una fuerte asociación entre el uso de comisiones de la verdad y la mejora en la protección de los derechos humanos. Incluso, los resultados muestran que la situación de los derechos humanos mejora aún más si las comisiones de la verdad hacen públicos sus informes y si recomiendan el enjuiciamiento de criminales de lesa humanidad. Este hallazgo respalda los resultados de otros estudios de justicia transicional que, desde un enfoque constructivista [@Kim2010], sostienen que el uso combinado de juicios y comisiones de la verdad genera un efecto disuasorio que contribuye significativamente a la no repetición, al aumentar los costos penales y simbólicos de la represión estatal [@Dancy2022].

En segundo lugar, los resultados del estudio @Dancy2022 señalan que el uso de una o más comisiones de la verdad mejora los niveles de participación democrática en los países, pero no tiene efectos sobre institucionales que garanticen el ejercicio de las libertades y civiles políticas. Es decir, no generan reformas que mejoran las instituciones que restringen el poder del ejecutivo o que garantizan el ejercicio colectivo de los derechos fundamentales. Lo que sí hace es aumentar los niveles de participación electoral y de las organizaciones de la sociedad civil en la toma de decisiones, incentivando a las personas que antes eran excluidas a integrarse a la vida pública.

## 2. Inconsistencias en los resultados de los estudios anteriores

Al comparar los hallazgos producidos por los cinco estudios reseñados anteriormente, se pueden observar importantes diferencias en cuanto a la contribución que hacen -de forma individual o combinada- los mecanismos de justicia transicional a la democracia y la protección de los derechos humanos en los regímenes de transición.

A nivel individual, los tres mecanismos de justicia transicional analizados presentan resultados inconsistentes. Los estudios de @Kim2010 y @Dancy2019 muestran una relación positiva entre el uso de enjuiciamientos y los niveles de protección de los derechos humanos en las democracias post autoritarias; mientras que el estudio de @Snyder2003 plantea que el enjuiciamiento está relacionado con un aumento de la represión estatal y un deterioro de las instituciones democráticas formales en los países que experimentaron conflictos internos o guerras civiles recientes. A su vez, @Olsen2010a presentan evidencia estadística que señala que el enjuiciamiento de criminales de lesa humanidad -por sí sólos- no mejora la protección de los derechos humanos ni los niveles de democracia en los países en transición.

La contribución individual de las amnistías a la protección de los derechos humanos también es diferente entre los estudios. Mientras @Snyder2003 presentan evidencia que sugiere que este mecanismo contribuye -por si sólo- a la protección de la democracia y los derechos humanos, @Dancy2019 afirman que las amnistías no mejoran los niveles de protección de los derechos humanos, pero sí impactan positivamente en el ejercicio de las libertades civiles y políticas durante los primeros años de transición.

En cuanto a las comisiones de la verdad, @Olsen2010a presentan evidencia de una relación negativa entre el uso individual de este mecanismo de justicia transicional y los niveles de protección de los derechos de integridad física en las democracias post autoritarias, mientras que @Dancy2022 y @Kim2010 muestran resultados que van en la dirección contraria.

A nivel combinado, los estudios muestran diferencias importantes relacionadas con la interacción entre el uso de enjuiciamientos, amnistías y comisiones de la verdad. Mientras @Olsen2010a presentan evidencia de que el uso combinado de juicios y amnistías, y de juicios, amnistías y comisiones de la verdad genera un efecto positivo en la democracia y la protección de los derechos humanos, porque contribuyen al equilibrio entre los impulsos de rendición de cuentas y la necesidad de estabilidad política presente en las democracias post autoritarias; @Dancy2019 muestran que el uso combinado de juicios y amnistías no genera efectos positivos en la protección de los derechos de integridad física y en el ejercicio de libertades civiles y política en los países en transición.

Varios factores ayudan a explicar la inconsistencia entre los hallazgos generados por los estudios anteriores. En la presente tesis de magister se destacan tres cuestiones principales que son el resultado del uso de métodos cuantitativos: la definición y medición de conceptos y variables de la justicia transicional; la elección de variables dependendientes como medidas de resultado; y las estrategias de muestreo entre países y tipos de transición.

### 2. 1. Diferencias en la definición y medición de la justicia transicional

En primer lugar, existe una carencia de definiciones taxativas y medidas uniformes. Cada mecanismo de justicia transicional parece ser conceptualizado y medido de manera distinta entre los académicos del campo.

Para @Olsen2010a, por ejemplo, en el contexto de una transición, el enjuiciamiento por violaciones de derechos humanos incluye una diversidad de sospechosos, como grupos rebeldes armados; agentes estatales que luchan en guerras civiles, realizan operaciones de contrainsurgencia o participan en la represión gubernamental; y grupos de oposición política interna. Además, estos autores codifican y registran los enjuiciamientos por violaciones de derechos humanos sólo cuando llegan a un veredicto. Con ello, plantean implícitamente la hipótesis de que el resultado, más que el proceso, es fundamental para cualquier impacto de los enjuiciamientos en la democracia y los derechos humanos. En cambio, @Kim2010 y @Dancy2019, siguiendo los lineamientos del derecho penal internacional, definen los enjuiciamientos como acciones penales dirigidas hacia agentes estatales acusados de violar derechos humanos. @Kim2010 consideran más importante el proceso que el resultado. Por eso, codifican acusaciones, arrestos, extradiciones, detenciones y juicios bajo la categoría general de enjuiciamientos. @Dancy2019 parten del mismo supuesto de @Kim2010, pero codifican tanto los enjuiciamientos como las condenas de criminales de lesa humanidad para medir el efecto disuasorio de los procesos y los resultados de la persecución penal.

Los estudios también varían significativamente en cómo definen operativamente las comisiones de la verdad. @Olsen2010a, @Kim2010 y @Dancy2022 entienden que una comisión de la verdad es un organismo temporal recientemente establecido y oficialmente sancionado por un estado o una organización gubernamental internacional para investigar un patrón de abusos contra los derechos humanos durante periodo histórico. Sin embargo, los autores mencionados utilizan diferentes criterios de inclusión de casos de comisiones de la verdad. @Olsen2010a, por ejemplo, incluyen casos de comisiones de la verdad que no investigan patrones de abusos sino eventos represivos particulares, como la Comisión Investigadora del Secuestro y Asesinato de los Representantes Nacionales Zelmar Michelini y Héctor Gutiérrez Ruiz en Uruguay. Algo similar ocurre con el estudio de @Dancy2022, cuya base de datos incluye casos de comisiones de la verdad celebradas dentro y fuera de un contexto de transición democrática o del término de una guerra civil, como la Comisión para la Verdad y la Reconciliación de Canadá, que investigó los abusos a los derechos humanos cometidos en los pensionados para niños indígenas entre las décadas de 1870 y 1940.

Además, los estudios que examinan las amnistías tampoco logran hacer distinciones cualitativas sólidas. @Snyder2003 y @Olsen2010a tratan las amnistías como variables ficticias. Dentro de esta categoría incluyen amnistías derivadas de acuerdos de paz o de transiciones negociadas, o que son dictadas por gobiernos post autoritarios o post conflicto en favor de criminales de guerra, criminales de lesa humanidad, miembros de grupos insurgentes, entre otros. En cambio, @Dancy2019 definen las amnistías como disposiciones legales que favorecen sólo a criminales de lesa humanidad procesados o condenados por los tribunales de justicia, y -en base a esa definición- cuentan el número de leyes o decretos de amnistías que son dictados en cada país en los años posteriores al retorno de la democracia.

### 2. 1. Diferencias en la elección de variables dependientes

En segundo lugar, los estudios comparados utilizan diferentes medidas de resultado para analizar la contribución de los mecanismos de justicia transicional a la democracia y la protección de los derechos humanos. Este problema es particularmente agudo en los estudios que analizan la contribución de los juicios, amnistías y comisiones de la verdad a la democratización de los países. La mayoría de los autores utilizan las escalas de democracia liberal de los proyectos CIRI, Freedom House y Polity IV [@Dancy2019; @Olsen2010a; @Snyder2003], mientras que otros utilizan indicadores desagregados de reformas institucionales y prácticas democráticas [@Dancy2022]. En ambos casos, los indicadores empleados dan cuenta de los niveles de participación, competencia y apertura electoral, de libertad de prensa, de libertad sindical, de control judicial sobre el poder ejecutivo y de otras dimensiones de la vida pública que poco tienen que ver con los objetivos manifiestos de verdad, justicia, reparación y garantías de no repetición que guían la implementación de los mecanismos de justicia transicional. Por tanto, resulta teóricamente problemático formular argumentos causales sobre el impacto de los mecanismos de justicia transicional en los aspectos de la democracia que son medidos por los proyectos CIRI, Freedom House y Polity IV. Sin embargo, otros aspectos que podrían ser más relevantes, como la ocurrencia de intentos de golpes de estado o de ataques armados en contra de la población civil, no han sido totalmente explorados hasta ahora.

Comparativamente hablando, existe un mayor consenso sobre las medidas utilizadas para juzgar el impacto de la justicia transicional en la protección de los derechos humanos. @Kim2010, @Olsen2010a y @Dancy2019, utilizan la medida de derechos humanos de Cingranelli y Richards (CIRI) [@Cingranelli2010], que se centra en la protección de los derechos de integridad física. @Olsen2010a también utilizan la Escala de Terror Político (PTS) [@Wood2010] como control de solidez para sus resultados. Tanto CIRI como PTS proporcionan puntuaciones de derechos humanos de los países basadas en informes anuales de derechos humanos elaborados por el Departamento de Estado de Estados Unidos y Amnistía Internacional, donde se reportan los casos de asesinatos, desapariciones forzadas, torturas y prisión política. En teoría, ambas medidas son útiles para analizar los posibles efectos disuasorios de los juicios, amnistías y comisiones de la verdad. Sin embargo, son comparativamente menos eficaces que el índice de integridad física latente desarrollado recientemente por [@Schnakenberg2013]. Este último indicador estima un puntaje de protección de los derechos humanos para cada año-país en base a un modelo bayesiano de respuesta al ítem ordinal que utiliza diferentes fuentes de información estadística, como las escalas de CIRI y PTS, y los indicadores del proyecto UPSALA/PRIIO que registran eventos represivos asociados a la violación masiva de los derechos de integridad física. Hasta ahora, el índice de integridad física latente ha estado restringido al estudio del impacto de las comisiones de la verdad [@Dancy2022]. Por tanto, es posible generar nuevo conocimiento utilizando este indicador para analizar la contribución de otros mecanismos de justicia transicional a la protección de los derechos humanos.

El desafío metodológico aquí es seleccionar y aplicar medidas de resultado adecuadas y coherentes para evaluar la contribución de la justicia transicional a la democracia y la protección de los derechos humanos. La selección de los indicadores y medidas de resultado debe basarse tanto en los argumentos teóricos de causalidad formulados por los enfoques de la justicia transicional como en la calidad metodológica de los indicadores disponibles.

### 2. 3. Diferencias en las estrategias de muestreo

En tercer lugar, los estudios comparados discrepan sobre el universo relevante de casos a analizar. Algunos consideran sólo los casos de países que experimentaron transiciones democráticas [@Dancy2019; @Kim2010] o post conflicto [@Snyder2003], y otros consideran ambos tipos de transiciones [@Dancy2022]. Estas diferencias en los criterios de selección de casos genera observaciones ampliamente divergentes para el análisis. Por tanto, no es posible generalizar los resultados entre los países que cerraron exitosamente un conflicto armado interno, y los países que experimentaron transiciones democráticas.

Lo mismo ocurre con los pasados autoritarios de los países que se analizan. Los estudios utilizan diferentes criterios de selección de casos. La mayoría utiliza muestras grandes que incluyen países con diferentes tipos de pasados autoritarios, como dictaduras cívico-militares, regímenes de partido único, teocracias étnico-religiosas, entre otras [@Dancy2019; @Dancy2022; @Olsen2010a]. Si bien el uso de muestras grandes supone una ventaja en términos cuantitativos, comparar los resultados de la justicia transicional en países con pasados autoritarios cualitativamente distintos puede ser problemático por varias razones:

a) **Contexto histórico y cultural**

Cada país y región tiene una historia, cultura y contexto político únicos. Los factores históricos, culturales y sociales pueden influir en la manera en que se abordan los abusos pasados y en cómo se perciben los procesos de justicia transicional. Lo que puede funcionar en un lugar podría no ser efectivo o adecuado en otro debido a estas diferencias. Los estudios analizados tratan de abordar este problema a través del uso de variables de control con alcance regional que no consideran las diferencias cualitativas (históricas, ligúisticas, culturales y geográficas) entre los países, lo que aumenta significativamente el riesgo de variable omitida.

b) **Naturaleza de los conflictos y abusos a los derechos humanos**

Los tipos de abusos, crímenes y conflictos son diferentes en cada región. Las circunstancias en las que ocurrieron los abusos y las dinámicas de los conflictos también son diversas. Durante las dictaduras cívico- militares en América Latina, especialmente en las décadas de 1970 y 1980, los abusos a los derechos humanos a menudo incluyeron desapariciones forzadas, tortura y ejecuciones extrajudiciales. Hubo una tendencia a la represión de movimientos sociales y políticos, así como a la censura de medios de comunicación y la persecución de opositores políticos de izquierda. En Asia, los abusos a los derechos humanos bajo regímenes autoritarios a menudo incluyeron represión contra minorías étnicas o religiosas, y la supresión de movimientos de independencia. En Europa del Este, durante la Guerra Fría, los regímenes comunistas impusieron un control estatal sobre la sociedad y restringieron severamente las libertades civiles y políticas. En europa occidental, las dictaduras de ultraderecha, como las de España y portugal, perpetraron abusos graves a los derechos humanos bajo un patròn orientado fundamentalmente contra determinados grupos étnicos, políticos y nacionalistas, que implicaron incluso la persecución de comunidades lingüísticas y minorías religiosas. Estas diferencias contextuales y de modalidades de represión pueden influir significativamente en la elección de los mecanismos de justicia transicional y en los desafíos específicos que enfrenta cada sociedad [@Stewart2017]. Sin embargo, es dificil que pueden ser captadas por las variables de control empleadas en los estudios cuantitativos.

c) **Recursos y capacidad institucional**

La capacidad de los países para llevar a cabo procesos de justicia transicional puede variar significativamente. Los países que recuperan una tradición democrática luego de un periodo excepcional de autoritarismo, suelen tener mayores recursos legales, sistemas judiciales más fortalecidos y una infraestructura institucional más adecuada para llevar a cabo investigaciones y enjuiciamientos exhaustivos en contra de los criminales de lesa humanidad, en comparación con los países que se independizan de regímenes autoritarios disueltos o que atraviesan periódicamente por conflictos armados de naturalesa étnica o religiosa. Estas diferencias de recursos y capacidad institucional puede afectar la elección y la eficacia histórica de los mecanismos de justicia transicional [@Carrasco2022].

En resumen, aunque existen principios generales de justicia transicional que son aplicables a los casos de países con pasados violentos o autoritarios, cada contexto regional es único y debe ser abordado teniendo en cuenta las características específicas de la sociedades en cuestión. La comparación directa entre países con diferentes legados violentos o autoritarios, o diferentes tipos de transición, puede simplificar en exceso los desafíos complejos y las consideraciones que están involucradas en cada caso.


## 3. Propuesta de Investigación

Los factores de inconsistencia señalados anteriormente representan importantes desafíos para la investigación empírica sobre la contribución de los mecanismos de justicia transicional a la democracia y la protección de los derechos humanos. En la presente tesis de magister se abordan estos desafíos a través de una estrategia de investigación novedosa que utiliza definiciones coherentes, datos y observaciones comparables, e indicadores adecuados que capturan las diferencias cuantitativas y cualitativas de los enjuciamientos, amnistías y comisiones de la verdad.

### 3. 1. Definiciones del derecho internacional e indicadores del TJRC

Para superar el desafío vinculado a la definición y medición de las variables de interés, se utilizan los conceptos del derecho internacional de los derechos humanos, y los indicadores desarrollados por el *Transitional Justice Research Collaborative* (TJRC).

En el derecho internacional, al igual que en la teoría sociológica, los mecanismos de justicia transicional son entendidos como tecnologías sociales que permiten abordar las consecuencias de los pasados autoritarios marcados por el uso masivo y sistemático de la violencia estatal [@Teitel2003]. Bajo esta definición, los estudios recientes, por ejemplo, codifican sólo los enjuiciamientos contra criminales de lesa humanidad y excluyen los juicios contra miembros de la resistencia armada, de grupos insurgentes o de partidos políticos de oposición al régimen autocrático (@Dancy2019). Este criterio resulta del todo adecuado si se considera que el resultado esperado del enjuiciamiento de violadores de derechos humanos es la disuasión de la conducta criminal entre los agentes del estado.

El TJRC es un proyecto académico que define y registra los enjuiciamientos, sentencias y amnistías por violaciones a los derechos humanos cuando estos refieren expresamente a delitos perpetrados por agentes estatales o por privados que operaron con su aquiescencia durante el pasado autoritario reciente. Por tanto, la definición de las variables de interés dentro de este conjunto de datos es consonante con la categorización formulada por los instrumentos del derecho internacional y las teorías sociológicas sobre el impacto de la justicia transicional.

Además, el TJRC dispone de una base de datos con variables que miden la frecuencia y calidad de los mecanismos de justicia transicional, a través de indicadores que dan cuenta del número de enjuiciamientos, sentencias y amnistías por violaciones de derechos humanos que son emitidas en cada año-país, al igual que el número de comisiones de la verdad que inician o culminan su mandato y que entregan recomendaciones de reforma o enjuiciamiento de criminales de lesa humanidad. También hay indicadores agregados de justicia transicional, como el número de enjuiciamientos, sentencias, amnistías y comisiones de la verdad acumuladas durante los años de transición, que permiten medir el avance de los países en estas materias.

A diferencia de los estudios que utilizan variables dicotómicas para medir el uso de juicios, amnistías y comisiones de la verdad, y contar los años de transición en los que se implementó cada uno de ellos [@Olsen2010a; @Kim2010], el uso de los datos del TJRC permite utilizar indicadores conceptualmente precisos que registran la frecuencia y la calidad de los mecanismos de justicia transicional. Lo cual supone una mejora significativa en la medición de las variables de interés.

### 3. 2. Medidas de protección de la democracia y los derechos humanos

Para abordar el desafío de la observación de resultados (elección de variables dependientes), se diseñaron modelos de análisis que buscan explicar la ocurrencia de golpes de Estado y la variación en los niveles de protección de los derechos humanos de integridad física, en base al uso individual y combinado de los mecanismos de justicia transicional.

La incorporación de los golpes de Estado como variables de resultado de la justicia transicional en la democracia se justifica en la medida que este indicador registra hechos que representan una amenaza real para la continuidad del proceso de transición. Según los académicos del enfoque realista de la justicia transicional [@Snyder2003], el uso de enjuiciamientos penales por violaciones de derechos humanos y de comisiones de la verdad que incentivan la rendición de cuentas judiciales puede activar a los potenciales saboteadores del proceso de transición, aumentando significativamente el riesgo de golpes de estado.

A diferencia de los estudios anteriores, que utilizaron diferentes medidas de resultado para medir la contribución de los mecanismos de justicia transicional a la democracia -desde indicadores agregados de democracia liberal hasta viables desagregadas de prácticas y reformas institucionales democráticas-, la presente tesis se enfoca sólo en medir la eficacia de la función manifiesta de la justicia transicional de prevenir la ocurrencia de golpes de estado que puedan poner en riesgo la continuidad del proceso de transición democrática. Al hacer esta reducción en el análisis de resultados, se cree que es posible establecer teóricamente un vínculo causal adecuado entre el uso de enjuiciamientos, amnistías y comisiones de la verdad, y la prevención de golpes de Estado en los países con democracias post autoritarias.

En cuanto a la protección de los derechos humanos, la presenta tesis utiliza Índice de Integridad Física Latente de @Schnakenberg2013, que estima el nivel de protección de los derechos de integridad física a través de un modelo dinámico de respuesta al ítem ordinal que incorpora la información disponible en otras fuentes de datos y reduce el sesgo de medición que generan los cambios en los estándares de derechos humanos a lo largo del tiempo [@Clark2013, 175-177] 

Cómo se explicará más adelante, el Índice de Integridad Física Latente de Schnakenberg y Fariss es el indicador más robusto de protección de los derechos humanos desarrollado hasta ahora [@Fariss2017]. Por ello, el uso de este indicador supone una mejora sustantiva en la medición del impacto de la justicia transicional en los países con democracias post autoritarias.

### 3. 3. Muestra de países de América Latina con pasados autoritarios recientes

Para superar los desafíos teóricos y metodológicos relacionados con las estrategias de muestreo y la comparabilidad de los casos de estudio, se diseñó una investigación empírica que analiza la contribución de los mecanismos de justicia transicional a la democracia y la protección de los derechos humanos sólo en los países de América Latina y el Caribe que experimentaron transiciones democráticas entre los años 1970 y 2010. La elección de este universo de estudio se basó en dos criterios teóricos y metodológicos.

El primer criterio, es la similitud de los pasados autoritarios recientes en la región. Durante los años 1970 y 1980, diez y siete de los treinta y tres países de América Latina y el Caribe fueron gobernados por dictaduras civiles y militares que violaron de forma sistemática y generalizada los derechos humanos. Todas ellas hicieron uso de la prisión política, la tortura, el asesinato y la desaparición forzada para eliminar la disidencia y mantener el control social de la población a través del terror estatal.

Según Manuel @Guerrero2023, el terrorismo de Estado latinoamericano se distingue sociológicamente de otras formas de violencia estatal masiva y unilateral (masacres) desarrolladas durante el siglo XX en los países de Europa, Asia y África, porque persigue fines y medios diferentes. Los regímenes autoritarios de América Latina hicieron uso de la violencia estatal para disciplinar a la población, y eliminar a los cuerpos disidentes, en base a un discurso político enfocado en el combate a la subversión y al comunismo internacional. En cambio, el genocidio en Ruanda (1994), la masacre de Srebrenica en Bosnia (1995) y el genocidio camboyano bajo el régimen de los Jemeres Rojos (década de 1970) son fenómenos de violencia estatal que involucraron el asesinato masivo y la persecución de comunidades étnicas o religiosas específicas, con el objetivo de eliminar para siempre a estos grupos.

En este sentido, al considerar sólo los casos de países de América Latina y el Caribe con pasados autoritarios recientes, se construye una muestra de análisis mucho más homogénea que la elaborada por los estudios anteriores. Lo que, en teoría, disminuye el sesgo de variable omitida y mejora los niveles de observación de los resultados y el desarrollo de vínculos causales entre los mecanismos de justicia transicional y la protección de la democracia y los derechos humanos. Sin embargo, la reducción del universo de análisis a los casos de un sólo continente implica también que sus resultados no son generalizables, y que, por tanto, no aplican a los países con regímenes post autoritarios desarrollados en otros contextos regionales.

El segundo criterio de selección de casos fueron los tipos de transiciones. En la presente tesis, se analiza la contribución de los mecanismos de justicia transicional a la democracia y la protección de los derechos humanos sólo en los países que experimentaron al menos un proceso de transición democrática entre los años 1970 y 2010. Bajo este criterio, se excluyeron del análisis países como Colombia que, aunque no tuvieron una dictadura en el sentido tradicional, experimentaron un conflicto armado interno de larga duración con grupos guerrilleros, paramilitares y narcotraficantes durante todo el periodo de estudio. Al hacer esta reducción del universo, se consideró que no es conveniente analizar sociológicamente los casos de transiciones que no son iguales, sin distinguir entre las transiciones democráticas, que son los casos emblemáticos de la justicia transicional [@Teitel2003; @Thoms2010], y los casos de países en conflicto interno que lidian con los crímenes de guerra y el *jus postbellum*.

En el próximo capítulo, se presentarán los objetivos de investigación  que guíaron el estudio de esta tesis, abordando los desafíos planteados por la literatura revisada. Dichos objetivos orientaran el desarrollo de un marco teórico y metodológico que permita analizar sociológicamente la relación entre el uso de uno o varios mecanismos de justicia transicional y los niveles de protección de la democracia y los derechos humanos en América Latina y el Caribe durante los últimos cincuenta años (o al menos, en el periodo que es posible medirla: 1970-2010).

