---
lang: es
output:
  word_document:
    reference_docx: formato_1.docx
    toc: yes
    fig_caption: yes
toc-title: Tabla de contenido
csl: apa.csl
bibliography: bibliografia.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# MARCO TEÓRICO

El marco teórico de esta tesis se centra en definir los conceptos clave de la investigación; es decir, los golpes de estado, la protección de los derechos humanos y la justicia transicional; y analizar su relación sobre la base de tres enfoques teóricos distintos desarrollados por los académicos del campo de estudio: el realismo, el constructivismo y el holismo.

Las definiciones y discusiones teóricos desarrollados en este capítulo son el fundamento desde el cual se derivan las hipótesis de investigación que analizan la contribución de los enjuiciamientos, amnistías y comisiones de la verdad a la prevención de golpes de estado y la protección de los derechos humanos en los países con regímenes políticos post autoritarios.

## 1. Conceptos clave

La definición de los conceptos centrales de la tesis se realiza en base a la literatura académica que utiliza las definiciones de la sociología, la ciencia política y el derecho penal internacional para referirse a los fenómenos relacionados con los golpes de estado, la protección de los derechos humano y el uso de mecanismos de justicia transicional (enjuiciamientos, amnistías y comisiones de la verdad).

### 1. 1. Golpes de estado

En la ciencia política los golpes de estado son definidos como intentos ilegales y abiertos por parte de los militares u otras élites dentro del aparato estatal de derrocar al ejecutivo en funciones [@Powell2011, 252]. Dentro de esta definición es posible distinguir dos tipos de golpes de estado, que se diferencian por la capacidad de agencia que tienen sus perpetradores. El primero, son los “golpes de oficiales de elite” que aluden a cualquier golpe exitoso o fallido llevado a cabo por el liderazgo militar de un país, compuesto por miembros del jefe de Estado Mayor, oficiales en consejos de mando y comandantes de las unidades funcionales de un ejército (ejército, fuerza aérea, marina). El segundo tipo, son los “golpes de oficiales de combate” que refieren a cualquier golpe exitoso o fallido planeado por oficiales de rango medio e inferior; Los conspiradores de esta última categoría pueden incluir oficiales individuales de rango superior, como oficiales con el rango de general o mayor, que no son miembros del liderazgo militar. La diferencia clave, según @Albrecht2018, es que los oficiales de élite son miembros de coaliciones gobernantes autoritarias, y los oficiales de combate no lo son (p. 318).

Considerando esta distinción, en la presente tesis se utiliza el término protección contra golpes de estado para referir a las estrategias destinadas a reducir la capacidad o los incentivos de las elites civiles y militares para dar un golpe [@Powell2012, 1018]. En el contexto de una transición las medidas empleadas por los países para protegerse de un golpe pueden ser muy variadas. Desde la aplicación de viejas y nuevas leyes de amnistía para oficiales de alto rango acusados de violar derechos humanos [@Snyder2003; @Vinjamuri2015], hasta la frecuente rotación del Alto Mando y la reorganización de las fuerzas armadas vía reforma institucional [@Talmadge2016]. La adopción de una o más de estas medidas está condicionada, obviamente, a variables del contexto político local, como el tipo de transición democrática, la capacidad de veto de la oposición y las cuotas de poder institucional que guardan los potenciales saboteadores del proceso.

### 1. 2. Protección de los derechos humanos

En las ciencias sociales, generalmente se utiliza el concepto de protección (de las violaciones) de los derechos humanos para referirse a las prácticas que buscan evitar la ocurrencia de actos ejercidos por agentes del Estado que atentan contra los derechos de integridad física de las personas que se encuentran bajo su jurisdicción [@Fariss2017; @Poe1999; @Richards2015]. Las violaciones a la integridad física incluyen la desaparición forzada, el asesinato, las ejecuciones sumarias o extrajudiciales, la tortura y otros tratos crueles, y la prisión política o arbitraria [@Cingranelli2010; @Schnakenberg2013; @Wood2010].

De acuerdo con lo establecido en el derecho internacional, las violaciones a los derechos de integridad física que constituyen violaciones de derechos humanos sólo pueden ser perpetradas, ordenadas o sancionadas por agentes del Estado, o por algún privado que opere con la anuencia de éste (Estatuto de Roma de La Corte Penal Internacional, 1998). Por tanto, el concepto de violación de derechos humanos describe materialmente los delitos cometidos por diferentes actores institucionales: los miembros del gobierno; los policías, guardias, personal de seguridad o cualquier otro tipo de agente encargado de velar por el orden público; los miembros de organizaciones militares o de organizaciones paramilitares; los miembros de las Fuerzas Armadas; los funcionarios de los servicios públicos; los agentes de los servicios de inteligencia; los miembros del sistema de justicia (donde se incluyen también las instituciones encargadas de cuidar a las personas que están bajo custodia del Estado); y/o los funcionarios de un Estado extranjero o de un Organismo Internacional [@Haschke2019].

Es importante señalar que el concepto de violación de derechos humanos empleado por las ciencias sociales no distingue entre aquellas violaciones a los derechos de integridad física que se cometen con motivos políticos y aquellas que no se comenten con motivos políticos, puesto que la doctrina y el enfoque del derecho internacional establece que las vulneraciones a los derechos fundamentales de las personas pueden ocurrir dentro o fuera de un contexto autoritario o represivo [@BuenoDeMesquita2005; @Davenport2004a; @Davenport2007a]. La tortura ejercida por agentes del Estado, por ejemplo, es considerada una violación a los derechos humanos, aunque esta no se desarrolle en el marco de una política terrorista o de exterminio dirigida contra las personas que forman parte de la oposición política de la dictadura o del gobierno democrático de turno [@Beger2019; @Conrad2018; @McGregor2013]. Por tanto, el régimen político y la motivación política es una variable independiente de la violencia estatal que conlleva violación a los derechos humanos, al igual que otras.

La literatura producida por los estudios macro cuantitativos muestra que la protección de los derechos humanos está fuertemente relacionada con el nivel de conflictividad de los países, el tipo de régimen político, el nivel de independencia del poder judicial y otras variables económicas y demográficas [@Keith2012]. Según estos estudios, la violencia estatal aumenta en aquellos países que atraviesan por conflictos armados (guerras civiles o guerras internacionales) [@Cingranelli2019] o que enfrentan periodos de revueltas o rebeliones sociales que conducen al uso de la acción represiva de las fuerzas de orden y seguridad frente al aumento de manifestaciones violentas [@Franklin2019; @Jackson2018]. Los estudios también relacionan la disminución de los niveles de violencia estatal con el aumento en los niveles de democracia, medidos a través la transformación en las prácticas y arreglos institucionales que regulan el ejercicio de poder y establecen un sistema vertical de rendición de cuentas [@BuenoDeMesquita2005; @Davenport2004a]. Además, en cuanto a las variables económicas y demográficas, la literatura muestra que los niveles de violencia estatal dependen del tamaño y crecimiento de la población, y del nivel de riqueza (PIB), de desigualdad y crecimiento económico de los países, ya que la probabilidad de que exista represión es mayor cuando los gobernantes y las fuerzas de orden y seguridad se enfrentan a poblaciones grandes y/o empobrecidas [@Keith2012].

### 1. 3. Justicia Transicional

El concepto de justicia transicional refiere a todas aquellas medidas implementadas por los gobiernos para enfrentar las consecuencias jurídicas, sociales y políticas que dejan los pasados violentos y/o autoritarios, marcados por el ejercicio de violaciones sistemáticas o generalizadas de los derechos humanos [@Teitel2003]. Las medidas de justicia transicional son implementadas generalmente en contextos de transición política (es decir, durante o después del término de una guerra civil o de una dictadura, y en medio de la reconstrucción democrática de un Estado) con el doble objetivo de a) entregar verdad, justicia y reparación a las víctimas y sus familiares, y b) garantizar la no repetición de las violaciones a los derechos humanos en el futuro [@InstitutoNacionaldeDerechosHumanos2017, 192]. Entre las medidas de justicia transicional se incluyen los juicios penales por violaciones a los derechos humanos, las amnistías, las comisiones de la verdad, las políticas de memorialización, los programas de reparación integral para las víctimas y sus familiares, la revisión de antecedentes, las purgas y las reformas institucionales. Sin embargo, las más estudiadas por los académicos a nivel cuantitativo son los juicios y las comisiones de la verdad [@Fariss2017; @Stewart2017; @Thoms2010].

#### 1. 3. a. Enjuiciamientos

En el contexto de una transición democrática, el enjuiciamiento es entendido como un proceso penal —que incluye juicios preliminares, audiencias de juicio y veredictos y sentencias— contra agentes estatales perpetradores de violaciones de derechos humanos que ocurrieron antes de la transición política al régimen democrático [@Dancy2019, 104]. Generalmente, los académicos examinan bajo este concepto los casos judiciales que operan en los tribunales nacionales de un país o en la Corte Penal Internacional u otros tribunales regionales o internacionales [@Kim2010; @Sikkink2011]. Sin embargo, estudios recientes sugieren que es conveniente analizar los efectos de esta variable incluyendo sólo los casos nacionales de responsabilidad penal individual, ya que éstos dan cuenta del nivel de compromiso estatal que se tiene con los derechos humanos [@Dancy2019].

Según la literatura científica existen cuatro factores clave relacionados con el uso o aumento de enjuiciamientos penales por violaciones de derechos humanos en los países en transición: la demanda de la sociedad civil, la ausencia de jugadores con veto, el liderazgo judicial nacional y la presión internacional [@Lessa2014]. El primer factor, se basa en la evidencia acumulada por los estudios de caso que demuestran que los movimientos locales de derechos humanos, compuestos por organizaciones de la sociedad civil que surgieron durante el régimen autoritario y que continúan movilizándose por la justicia durante y después de la transición democrática, tienen los recursos políticos y organizativos para demandar eficazmente el enjuiciamiento de los criminales de lesa humanidad, y combatir la impunidad que genera el uso de amnistías. El segundo factor, se basa en la importancia que tiene la ausencia o presencia de jugadores con veto en los procesos de justicia transicional. Es decir, de actores poderosos que podrían oponerse a la rendición de cuentas o la investigación de las violaciones de derechos humanos ocurridas en el pasado. En este sentido, la presencia de jugadores con veto suele estar asociada con altos niveles de impunidad, mientras que la ausencia de ellos facilita los procesos de enjuiciamiento. El tercer factor hace referencia al rol que desempeñan los abogados particulares, los jueces y otros actores locales del sistema judicial en las democracias post autoritarias. Un poder judicial independiente que conozca los principios democráticos del derecho a reparación y las normas internacionales de derechos humanos puede estar dispuesto a desafiar la impunidad e incentivar la rendición de cuentas, tanto en el corto como en el largo plazo. El cuarto factor refiere a la presión que ejerce la comunidad internacional a través de las obligaciones legales incorporadas en tratados y fallos de tribunales regionales. Los acuerdos internacionales de derechos humano que son jurídicamente vinculantes establecen expresamente el deber de los Estados de enjuiciar a los funcionarios públicos que cometan o hayan cometido delitos tipificados en la Convención para la Prevención y la Sanción del Genocidio [-@ONU1948], la Convención contra la Tortura y Otros Tratos o Penas Crueles, Inhumanos o Degradantes [-@ONU1984], la Convención Internacional para la Protección de todas las Personas contra las Desapariciones Forzadas [-@ONU2010], la Convención de Ginebra [-@ONU1949] y el Estatuto de Roma de la Corte Penal Internacional [-@CPI1998].

#### 1. 3. b. Amnistías

En la presente tesis, utilizaremos el término “amnistía” para hacer referencia a las disposiciones legislativas, constitucionales o ejecutivas vigentes que otorgan inmunidad judicial por violaciones de derechos humanos cometidas por agentes estatales durante el régimen autoritario anterior [@Dancy2019, 104]. Generalmente, las amnistías son políticas gubernamentales propuestas por presidentes, dictadores o legisladores y, por lo general, solo confirmadas o impugnadas por procesos judiciales, que buscan garantizar la estabilidad política de los procesos de transición [@Snyder2003; @Vinjamuri2015].

Según los autores que promueven el uso de amnistías en los procesos de transición, el principal factor asociado a la mantención o adopción de estas leyes es la necesidad que tienen los gobiernos emergentes de garantizar la estabilidad política y el estado de derecho, evitando cualquier tipo de insurrección por parte de los potenciales agentes saboteadores [@Snyder2003; @Vinjamuri2015]. Por ello, la amnistía para violadores de derechos humanos puede ser entendida como una medida de protección contra los golpes de estado.

#### 1. 3. c. Comisiones de la Verdad

Por su parte, las comisiones de la verdad refieren a organismos temporales y oficialmente sancionados, que se constituyen con el mandato de investigar períodos específicos de abusos estatales ocurridos en el pasado [@Dancy2022; @Kim2019; @Olsen2010]. Su finalidad explícita es establecer la verdad sobre los abusos pasados y evitar que se repitan en el futuro [@Hayner2008]. Por lo mismo, una Comisión de Verdad puede: a) proporcionar un reconocimiento oficial de las violaciones de derechos humanos del pasado, reescribiendo la historia; b) centrarse en los factores institucionales y estructurales que permitieron tales abusos; c) hacer recomendaciones para reformas legales e institucionales; d) proporcionar información que sea útil para los enjuiciamientos posteriores y la investigación de antecedentes entre los miembros abusivos de las fuerzas de orden y seguridad; y e) crear un listado oficial de víctimas que permita la realización de políticas de memorialización y de reparación integral (Hayner, 2008; Rivas, 2016).

Las investigaciones sobre justicia transicional afirman que el cumplimiento de los objetivos de prevención de violaciones a los derechos humanos de una comisión de verdad depende, en gran medida, de la calidad de estas. Es decir, de si la comisión en cuestión emite o no un informe público, y de si hace o no recomendaciones de reformas o entrega información importante para la realización de juicios penales por abusos del pasado [@Bakiner2014; @Dancy2022]. Por tanto, es conveniente distinguir cada una de estas operaciones en indicadores diferentes que permitan monitorear las prácticas asociadas a las comisiones de la verdad y medir su contribución a la no repetición.

Según un estudio reciente de @Kim2019, la adopción de una comisión de verdad por parte de los gobiernos democráticos post autoritarios depende significativamente de dos factores clave: las redes transnacionales (locales y extranjeras) de promoción de las comisiones de la verdad, y la difusión de la experiencia de una comisión de verdad entre los países vecinos. La existencia de organizaciones y movimientos de derechos humanos activos y fuertes es un factor significativo que afecta la decisión de un estado de establecer una comisión de verdad. El efecto que puede producir un movimiento nacional de derechos humanos sobre la adopción gubernamental de una comisión de verdad es aún mayor si su demanda de verdad es apoyada por organismos del sistema de Naciones Unidas y otras organizaciones no gubernamentales de carácter transnacional. Además, el estudio muestra que los gobiernos de los países con democracias post autoritarias son más propensos a adoptar una comisión de verdad si uno de sus países vecinos ya lo ha hecho. Este efecto de difusión se produce al compartir experiencias de justicia transicional entre países con características culturales, geográficas y políticas similares (por ejemplo, entre las democracias post autoritarias instauradas en América Latina luego del periodo de dictaduras de seguridad nacional de los años 1970 y 1980).

Además de los dos factores clave mencionados, el estudio de @Kim2019 muestra que la adopción de una comisión de la verdad también está relacionada con el nivel de democracia y desarrollo económico alcanzado por los países en transición. Los países con un alto nivel de democracia, medidos por la puntuación polity IV, parecen ser más propensos a establecer comisiones de la verdad que los países con bajos niveles de democracia o que enfrentan periodos autoritarios. Asimismo, los datos de estudio muestran que los gobiernos post autoritarios de los países con recursos económicos crecientes son más propensos a adoptar comisiones de la verdad que los que atraviesan por periodos de crisis o bajo crecimiento económico, ya que pueden dedicar más esfuerzos políticos a las cuestiones relacionadas con las violaciones de los derechos humanos ocurridas en el pasado.

## 2. Teorías e hipótesis de investigación

Según @Dancy2019 y @Stewart2017, la investigación empírica sobre justicia transicional, democracia y protección de los derechos humanos presentada en el Capítulo II. 1., ha generado tres enfoques teóricos y normativos contrapuestos: el realismo político, el constructivismo y el holismo. En base a cada uno de estos enfoques es posible formular diferentes hipótesis de investigación sobre la contribución de los enjuiciamientos, amnistías y comisiones de la verdad a la prevención de golpes de estado y la protección de los derechos humanos en las democracias post autoritarias.

### 2. 1. Enfoque realista

El realismo político es el enfoque promovido por los académicos de la justicia transicional que cuestionan la adopción de políticas de rendición de cuentas en derechos humanos que puedan alterar el equilibrio de "intereses políticos dominantes" en la transición y poner en riesgo la nueva democracia [@Snyder2003; @Vinjamuri2015]. La hipótesis central de estos autores es que los gobiernos post autoritarios que llevan adelante enjuiciamientos penales contra ex violadores de derechos humanos enfrentarán una mayor amenaza de golpes militares y rebeliones violentas, y tendrán más partidos insatisfechos que cuestionen la legitimidad de la nueva democracia [@Snyder2003]. Por tanto, bajo este enfoque, las amnistías y la impunidad son vistas como males necesarios; es decir, como medidas responsables que buscan garantizar la estabilidad política y el estado de derecho; mientras que el enjuiciamiento penal, la revisión de antecedentes, y la realización de reformas institucionales a las fuerzas de orden y seguridad son vistas como medidas temerarias, que, al afectar al personal represivo de la autocracia saliente, ponen en riesgo la democracia y la protección de los derechos humanos, sobre todo durante los primeros años de transición, que es el periodo en el que los potenciales saboteadores del proceso aún guardan importantes cuotas de poder institucional.

El enfoque realista considera que las comisiones de verdad son potencialmente menos desestabilizadoras para las democracias que los enjuiciamientos penales, sobre todo si consideran el otorgamiento de amnistías para los criminales de lesa humanidad que contribuyan con la investigación [@Olsen2010a, 987]. En cambio, si las comisiones de verdad publican informes oficiales que recomienden el enjuiciamiento de los violadores de derechos humanos o la implementación de reformas estructurales a las fuerzas de orden y seguridad, generarán mayor riesgo de golpes de estado y de interrupción del proceso de transición democrática.

Desde el enfoque realista se pueden formular las siguientes hipótesis:

-	Hipótesis 1 (a): El aumento en el número de enjuiciamientos y condenas por violaciones de derechos humanos estará asociado con un aumento en el número de intentos de golpes de estado en los procesos de transición democrática

-	Hipótesis 1 (b): El aumento en el número de amnistías para violadores de derechos humanos estará asociado con una disminución de los intentos de golpes de estado en los procesos de transición democrática

-	Hipótesis 1 (c) La combinación de comisiones de verdad y enjuiciamientos por violaciones de derechos humanos estará asociada con un aumento en el número de intentos de golpes de estado en los procesos de transición democrática

-	Hipótesis 1 (d): La combinación de comisiones de verdad y amnistías para violadores de derechos humanos estará asociada con una disminución de los intentos de golpes de estado en los procesos de transición democrática

### 2. 2. Enfoque constructivista

El segundo enfoque, el enfoque constructivista, reúne a los académicos que argumentan que los cambios legales internacionales y domésticos en materia de rendición de cuentas, y los esfuerzos de los activistas de derechos humanos y de los grupos pro-justicia que presionan a sus gobiernos, crean una demanda de justicia transicional por cambios institucionales y prácticos que ha contribuido significativamente a la no repetición [@Dancy2019; @Dancy2022; @Kim2010]. Estas normas y prácticas han modificado las percepciones de los actores sobre sus intereses y sus estrategias, ya que aumentan los costos penales, simbólicos y políticos asociados a la represión [@Sikkink2011; @Sikkink2013].

Los académicos del enfoque constructivista, a diferencia de los realistas, han demostrado empíricamente sus afirmaciones, presentando evidencia estadística que sugiere que los enjuiciamientos penales de derechos humanos están asociados con menos violaciones a los derechos de integridad física en el largo plazo [@Dancy2019; @Kim2010]. Esto se debe a que la socialización normativa y el castigo material por violaciones de derechos humanos genera un efecto disuasorio que contribuye a mejorar la protección de los derechos de integridad física en las democracias post autoritarias [@Sikkink2011].

Los estudios constructivistas sobre las comisiones de verdad muestran que este mecanismos de justicia transicional también puede contribuir significativamente a la protección de los derechos humanos en las democracias post autoritarias, en la medida que aumenta los costos simbólicos para los agentes represores [@Kim2010]. En este sentido, el enfoque constructivista asume que las comisiones de verdad, al igual que los juicios, cumplen una poderosa función comunicativa en las sociedades con democracias post autoritarias, ya que pueden propagar el estigma asociado a las violaciones a los derechos humanos ocurridas en el pasado autoritario. Además, si una comisión de verdad culmina con la publicación de un informe recomendando reformas o enjuiciamientos, entonces podrá reforzar la percepción de que los agentes y las instituciones estatales serán penal y políticamente responsables en el futuro, contribuyendo así a la prevención de la violencia política en las democracias post-autoritarias [@Dancy2022].

Desde el enfoque constructivista es posible formular las siguientes hipótesis:

-	Hipótesis 2 (a): El aumento en el número de enjuiciamientos y condenas por violaciones de derechos humanos estará asociado con un aumento en el nivel de protección de los derechos de integridad física.

-	Hipótesis 2 (b): El aumento en el número de comisiones de verdad celebradas en las transiciones democráticas estará asociado con un aumento en el nivel de protección de los derechos de integridad física.

-	Hipótesis 2 (c): La recomendación de enjuiciamientos que emiten las comisiones de verdad estará asociada con un aumento en el nivel de protección de los derechos de integridad física.

### 2. 3. Enfoque hoslista

El enfoque holista es aquel que reúne a los académicos que sostienen que la negociación para la estabilidad política y la disuasión criminal son procesos paralelos y necesarios para garantizar la paz, el estado de derecho y la protección de la integridad física y las libertades civiles de las personas en las transiciones democráticas. La perspectiva holística sostiene que los juicios y las amnistías funcionan en combinación y de manera complementaria para mejorar los derechos humanos y los resultados democráticos [@Olsen2010a]. Olsen, Payne & Reiter [-@Olsen2010a,147–148] desarrollaron este enfoque del "equilibrio de justicia", al afirmar que la combinación de juicios y amnistías es aditiva y que trabajan en conjunto para proporcionar "un término medio entre la rendición de cuentas y el apaciguamiento".

Bajo este enfoque, las comisiones de verdad son vistas como medidas complementarias que contribuyen al equilibrio entre el impulso de rendición de cuentas y los imperativos de estabilidad política que imponen los procesos de transición a través de las amnistías [@Olsen2010]. Son entendidas como medidas complementarias al uso de juicios y amnistías porque, por sí solas, las comisiones de verdad no logran el objetivo de contribuir a la no repetición, ya que no son capaces de dar acceso a la justicia, ni de garantizar la estabilidad política de los procesos de transición. Sin embargo, cuando las comisiones van acompañadas de juicios y amnistías, pueden contribuir significativamente a la rendición de cuentas y la estabilidad política que brindan esos mecanismos a través del otorgamiento de incentivos para la colaboración de agentes del régimen anterior y la publicación de informes con recomendaciones para garantizar la no repetición de las violaciones a los derechos humanos [@Olsen2010].

Según @Zalaquett1991, la adopción de medidas de justicia transicional bajo el enfoque holista va asociada a un entendimiento sociológico del quehacer político de los gobiernos en una transición democrática, que es la combinación de la ética de la convicción y la ética de la responsabilidad al momento de tomar decisiones.  En este sentido, los holistas proponen avanzar todo lo que se pueda en verdad, justicia, reparación y no repetición, sin poner en riesgo la democracia y el estado de derecho. Sugieren, por tanto, realizar la mayor cantidad posible de juicios y comisiones de verdad, manteniendo una cantidad mínima de amnistías y de agentes impunes que permita apaciguar a las fuerzas defensoras del ex régimen autocrático durante los primeros años de transición.

Desde el enfoque holista es posible formular las siguientes hipótesis:

-	Hipótesis 3 (a): La combinación de juicios y amnistías estará asociada con un aumento en el nivel de respeto de los derechos de integridad física.

-	Hipótesis 3 (b): La combinación de juicios, amnistías y comisiones de verdad estará asociada con un aumento en el nivel de respeto de los derechos de integridad física.

